"use client";
import { Wrench, Calendar, Clock, AlertTriangle, CheckCircle, IndianRupee } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { mockMaintenanceItems, mockServiceHistory } from "@/lib/mockData";
import { formatCurrency, formatDate, getSeverityColor } from "@/lib/utils";
import Link from "next/link";

const urgencyBadge: Record<string, "red" | "amber" | "blue" | "green"> = {
  critical: "red", high: "red", medium: "amber", low: "green",
};

export default function MaintenancePage() {
  const totalEstimated = mockMaintenanceItems.reduce(
    (sum, m) => sum + (m.estimatedCostMin + m.estimatedCostMax) / 2, 0
  );

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="page-header">
        <h1 className="text-2xl font-bold text-aegis-navy">Predictive Maintenance</h1>
        <p className="text-sm text-slate-500 mt-0.5">AI-driven service recommendations · Complete history</p>
      </div>

      {/* Summary strip */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: "Active Recommendations", value: mockMaintenanceItems.length, icon: Wrench,       color: "text-status-amber" },
          { label: "Overdue Items",           value: mockMaintenanceItems.filter(m=>m.isOverdue).length, icon: AlertTriangle, color: "text-status-red" },
          { label: "Est. Cost Range",         value: formatCurrency(totalEstimated), icon: IndianRupee, color: "text-status-blue" },
          { label: "Service Records",         value: mockServiceHistory.length, icon: CheckCircle,   color: "text-status-green" },
        ].map(({ label, value, icon: Icon, color }) => (
          <Card key={label}>
            <p className="text-[10px] text-slate-400 uppercase tracking-wide mb-1">{label}</p>
            <div className="flex items-end justify-between">
              <p className={`text-2xl font-bold ${color}`}>{value}</p>
              <Icon size={18} className={color} />
            </div>
          </Card>
        ))}
      </div>

      {/* Active recommendations */}
      <Card title="Active Recommendations" subtitle="Generated by AEGIS Maintenance Optimizer">
        <div className="space-y-3 mt-2">
          {mockMaintenanceItems.map((item) => (
            <div key={item.id} className="border border-slate-100 rounded-xl p-4 hover:border-slate-200 hover:shadow-card transition-all">
              <div className="flex items-start justify-between gap-3 mb-3">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <p className="font-semibold text-slate-800 text-sm">{item.title}</p>
                    <Badge variant={urgencyBadge[item.urgency]}>{item.urgency.toUpperCase()}</Badge>
                  </div>
                  <p className="text-xs text-slate-500">{item.description}</p>
                </div>
                <div className="text-right flex-shrink-0">
                  <p className="text-xs text-slate-400">Est. cost</p>
                  <p className="text-sm font-semibold text-slate-800">
                    {formatCurrency(item.estimatedCostMin)} – {formatCurrency(item.estimatedCostMax)}
                  </p>
                </div>
              </div>

              <div className="bg-slate-50 rounded-lg p-2.5 mb-3">
                <p className="text-[11px] text-slate-600">
                  <span className="font-semibold text-aegis-navy">Why now: </span>
                  {item.triggerReason}
                </p>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3 text-xs text-slate-500">
                  {item.dueKm && (
                    <span className="flex items-center gap-1"><Clock size={11} /> Due in {(item.dueKm - (item.currentKm ?? 0)).toLocaleString("en-IN")} km</span>
                  )}
                  {item.dueDate && (
                    <span className="flex items-center gap-1"><Calendar size={11} /> Due {formatDate(item.dueDate)}</span>
                  )}
                </div>
                <Link href="/dealers" className="aegis-btn-primary py-1.5 px-3 text-xs">
                  Book Service →
                </Link>
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Service history */}
      <Card title="Service History" subtitle="Complete immutable log — digitally stamped by AEGIS dealers">
        <div className="mt-2 space-y-3">
          {mockServiceHistory.map((rec) => (
            <div key={rec.id} className="flex gap-4 p-4 border border-slate-100 rounded-xl">
              <div className="w-1 bg-aegis-navy rounded-full flex-shrink-0" />
              <div className="flex-1">
                <div className="flex items-start justify-between mb-1">
                  <div>
                    <p className="text-sm font-semibold text-slate-800">{rec.description}</p>
                    <p className="text-xs text-slate-500">{rec.dealerName} · {formatDate(rec.date)}</p>
                  </div>
                  <Badge variant={rec.type === "routine" ? "green" : rec.type === "emergency" ? "red" : "blue"}>
                    {rec.type.replace("_", " ")}
                  </Badge>
                </div>
                {rec.partsReplaced.length > 0 && (
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    {rec.partsReplaced.map((p) => (
                      <span key={p} className="text-[10px] bg-slate-100 text-slate-600 rounded-full px-2 py-0.5">{p}</span>
                    ))}
                  </div>
                )}
                <div className="flex items-center justify-between mt-2">
                  <p className="text-xs text-slate-500">
                    {rec.nextServiceKm && `Next service: ${rec.nextServiceKm.toLocaleString("en-IN")} km`}
                    {rec.nextServiceDate && ` / ${formatDate(rec.nextServiceDate)}`}
                  </p>
                  <p className="text-sm font-semibold text-aegis-navy">{formatCurrency(rec.totalCostRs)}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
